server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/gateway/auth/**
          filters:
            - StripPrefix=1

        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/gateway/applications/**
          filters:
            - StripPrefix=1

        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/gateway/documents/**
          filters:
            - StripPrefix=1

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/gateway/admin/**
          filters:
            - StripPrefix=1

        - id: products
          uri: lb://application-service
          predicates:
            - Path=/gateway/products/**
          filters:
            - StripPrefix=1

jwt:
  secret: finflow-super-secret-key-must-be-at-least-256-bits-long-for-hs256
